services:
  postgres:
    image: postgres:16-alpine
    container_name: workspot-postgres
    environment:
      POSTGRES_USER: workspot
      POSTGRES_PASSWORD: workspot
      POSTGRES_DB: workspot
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
